//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace UPS.Service.XAVService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="XAVBinding", Namespace="http://www.ups.com/WSDL/XOLTWS/XAV/v1.0")]
    public partial class XAVService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private UPSSecurity uPSSecurityValueField;
        
        private System.Threading.SendOrPostCallback ProcessXAVOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public XAVService() {
            this.Url = global::UPS.Service.Properties.Settings.Default.UPS_Service_XAVService_XAVService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UPSSecurity UPSSecurityValue {
            get {
                return this.uPSSecurityValueField;
            }
            set {
                this.uPSSecurityValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcessXAVCompletedEventHandler ProcessXAVCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/XAVBinding/v1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("XAVResponse", Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
        public XAVResponse ProcessXAV([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")] XAVRequest XAVRequest) {
            object[] results = this.Invoke("ProcessXAV", new object[] {
                        XAVRequest});
            return ((XAVResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessXAVAsync(XAVRequest XAVRequest) {
            this.ProcessXAVAsync(XAVRequest, null);
        }
        
        /// <remarks/>
        public void ProcessXAVAsync(XAVRequest XAVRequest, object userState) {
            if ((this.ProcessXAVOperationCompleted == null)) {
                this.ProcessXAVOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessXAVOperationCompleted);
            }
            this.InvokeAsync("ProcessXAV", new object[] {
                        XAVRequest}, this.ProcessXAVOperationCompleted, userState);
        }
        
        private void OnProcessXAVOperationCompleted(object arg) {
            if ((this.ProcessXAVCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessXAVCompleted(this, new ProcessXAVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", IsNullable=false)]
    public partial class UPSSecurity : System.Web.Services.Protocols.SoapHeader {
        
        private UPSSecurityUsernameToken usernameTokenField;
        
        private UPSSecurityServiceAccessToken serviceAccessTokenField;
        
        /// <remarks/>
        public UPSSecurityUsernameToken UsernameToken {
            get {
                return this.usernameTokenField;
            }
            set {
                this.usernameTokenField = value;
            }
        }
        
        /// <remarks/>
        public UPSSecurityServiceAccessToken ServiceAccessToken {
            get {
                return this.serviceAccessTokenField;
            }
            set {
                this.serviceAccessTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityUsernameToken {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
    public partial class CandidateType {
        
        private AddressClassificationType addressClassificationField;
        
        private AddressKeyFormatType addressKeyFormatField;
        
        /// <remarks/>
        public AddressClassificationType AddressClassification {
            get {
                return this.addressClassificationField;
            }
            set {
                this.addressClassificationField = value;
            }
        }
        
        /// <remarks/>
        public AddressKeyFormatType AddressKeyFormat {
            get {
                return this.addressKeyFormatField;
            }
            set {
                this.addressKeyFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
    public partial class AddressClassificationType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
    public partial class AddressKeyFormatType {
        
        private string consigneeNameField;
        
        private string attentionNameField;
        
        private string[] addressLineField;
        
        private string politicalDivision2Field;
        
        private string politicalDivision1Field;
        
        private string postcodePrimaryLowField;
        
        private string postcodeExtendedLowField;
        
        private string regionField;
        
        private string urbanizationField;
        
        private string countryCodeField;
        
        /// <remarks/>
        public string ConsigneeName {
            get {
                return this.consigneeNameField;
            }
            set {
                this.consigneeNameField = value;
            }
        }
        
        /// <remarks/>
        public string AttentionName {
            get {
                return this.attentionNameField;
            }
            set {
                this.attentionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressLine")]
        public string[] AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
            }
        }
        
        /// <remarks/>
        public string PoliticalDivision2 {
            get {
                return this.politicalDivision2Field;
            }
            set {
                this.politicalDivision2Field = value;
            }
        }
        
        /// <remarks/>
        public string PoliticalDivision1 {
            get {
                return this.politicalDivision1Field;
            }
            set {
                this.politicalDivision1Field = value;
            }
        }
        
        /// <remarks/>
        public string PostcodePrimaryLow {
            get {
                return this.postcodePrimaryLowField;
            }
            set {
                this.postcodePrimaryLowField = value;
            }
        }
        
        /// <remarks/>
        public string PostcodeExtendedLow {
            get {
                return this.postcodeExtendedLowField;
            }
            set {
                this.postcodeExtendedLowField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string Urbanization {
            get {
                return this.urbanizationField;
            }
            set {
                this.urbanizationField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class CodeDescriptionType {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class ResponseType {
        
        private CodeDescriptionType responseStatusField;
        
        private CodeDescriptionType[] alertField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        public CodeDescriptionType ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Alert")]
        public CodeDescriptionType[] Alert {
            get {
                return this.alertField;
            }
            set {
                this.alertField = value;
            }
        }
        
        /// <remarks/>
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class TransactionReferenceType {
        
        private string customerContextField;
        
        private string transactionIdentifierField;
        
        /// <remarks/>
        public string CustomerContext {
            get {
                return this.customerContextField;
            }
            set {
                this.customerContextField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionIdentifier {
            get {
                return this.transactionIdentifierField;
            }
            set {
                this.transactionIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
    public partial class RequestType {
        
        private string[] requestOptionField;
        
        private TransactionReferenceType transactionReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestOption")]
        public string[] RequestOption {
            get {
                return this.requestOptionField;
            }
            set {
                this.requestOptionField = value;
            }
        }
        
        /// <remarks/>
        public TransactionReferenceType TransactionReference {
            get {
                return this.transactionReferenceField;
            }
            set {
                this.transactionReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")]
    public partial class UPSSecurityServiceAccessToken {
        
        private string accessLicenseNumberField;
        
        /// <remarks/>
        public string AccessLicenseNumber {
            get {
                return this.accessLicenseNumberField;
            }
            set {
                this.accessLicenseNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
    public partial class XAVRequest {
        
        private RequestType requestField;
        
        private string regionalRequestIndicatorField;
        
        private string maximumCandidateListSizeField;
        
        private AddressKeyFormatType addressKeyFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public RequestType Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public string RegionalRequestIndicator {
            get {
                return this.regionalRequestIndicatorField;
            }
            set {
                this.regionalRequestIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string MaximumCandidateListSize {
            get {
                return this.maximumCandidateListSizeField;
            }
            set {
                this.maximumCandidateListSizeField = value;
            }
        }
        
        /// <remarks/>
        public AddressKeyFormatType AddressKeyFormat {
            get {
                return this.addressKeyFormatField;
            }
            set {
                this.addressKeyFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0")]
    public partial class XAVResponse {
        
        private ResponseType responseField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private AddressClassificationType addressClassificationField;
        
        private CandidateType[] candidateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")]
        public ResponseType Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AmbiguousAddressIndicator", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NoCandidatesIndicator", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ValidAddressIndicator", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public AddressClassificationType AddressClassification {
            get {
                return this.addressClassificationField;
            }
            set {
                this.addressClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Candidate")]
        public CandidateType[] Candidate {
            get {
                return this.candidateField;
            }
            set {
                this.candidateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ups.com/XMLSchema/XOLTWS/xav/v1.0", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        AmbiguousAddressIndicator,
        
        /// <remarks/>
        NoCandidatesIndicator,
        
        /// <remarks/>
        ValidAddressIndicator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ProcessXAVCompletedEventHandler(object sender, ProcessXAVCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessXAVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessXAVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public XAVResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((XAVResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591