//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessorialCharge
    {
        public AccessorialCharge()
        {
            this.AccessorialChargeAmounts = new HashSet<AccessorialChargeAmount>();
        }
    
        public System.Guid Id { get; set; }
        public string AccessorialChargeName { get; set; }
    
        public virtual ICollection<AccessorialChargeAmount> AccessorialChargeAmounts { get; set; }
    }
}
