//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessorialChargeAmount
    {
        public System.Guid Id { get; set; }
        public decimal Content { get; set; }
        public string Remarks { get; set; }
        public System.Guid AccessorialChargeId { get; set; }
        public string CustomerAccountId { get; set; }
    
        public virtual AccessorialCharge AccessorialCharge { get; set; }
        public virtual CustomerAccount CustomerAccount { get; set; }
    }
}
