//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressBookInfo
    {
        public System.Guid Id { get; set; }
        public string NickName { get; set; }
        public string CompanyOrName { get; set; }
        public string Contact { get; set; }
        public string Country { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public bool IsResidential { get; set; }
        public string Telephone { get; set; }
        public string Extension { get; set; }
        public string Fax { get; set; }
        public string EmailAddress { get; set; }
        public string LocationID { get; set; }
        public bool SaveAsShipperFromFlag { get; set; }
        public string ReceiverUPSAccount { get; set; }
        public string ReceiverPostalCode { get; set; }
        public string ReferenceType1 { get; set; }
        public string ReferenceType2 { get; set; }
        public System.Guid OwnerOfAddressBook_Id { get; set; }
        public Nullable<System.Guid> Customer_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
