//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignee
    {
        public Consignee()
        {
            this.ShipmentRequests = new HashSet<ShipmentRequest>();
            this.Customers = new HashSet<Customer>();
        }
    
        public System.Guid Id { get; set; }
        public string AddressBookName { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeAddress1 { get; set; }
        public string ConsigneeAddress2 { get; set; }
        public string ConsigneeAddress3 { get; set; }
        public string ConsigneeCity { get; set; }
        public string ConsigneeStateOrProvince { get; set; }
        public string COnsigneePostalOrZip { get; set; }
        public string ConsigneeCountry { get; set; }
        public string ConsigneeContactPerson { get; set; }
        public string ConsigneePhone { get; set; }
        public string ConsigneePhoneExt { get; set; }
        public string ConsigneeEmail { get; set; }
        public Nullable<bool> ConsigneeIsResidential { get; set; }
        public string UPSId { get; set; }
    
        public virtual ICollection<ShipmentRequest> ShipmentRequests { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
