//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSpInstructionAmount
    {
        public System.Guid Id { get; set; }
        public decimal CustomerAmount { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid SpecialInstructionId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SpecialInstruction SpecialInstruction { get; set; }
    }
}
