//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.AddressBookInfoes = new HashSet<AddressBookInfo>();
            this.CustomerAccounts = new HashSet<CustomerAccount>();
            this.CustomerMarkups = new HashSet<CustomerMarkup>();
            this.CustomerShipments = new HashSet<CustomerShipment>();
            this.CustomerSpInstructionAmounts = new HashSet<CustomerSpInstructionAmount>();
            this.ShipmentRequests = new HashSet<ShipmentRequest>();
            this.Consignees = new HashSet<Consignee>();
            this.Roles = new HashSet<Role>();
        }
    
        public System.Guid Id { get; set; }
        public string CustomerName { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string PhoneExt { get; set; }
        public string Fax { get; set; }
        public string AltPhone { get; set; }
        public string AltContactPerson { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string SalesRepresentative { get; set; }
        public decimal CommissionRate { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UPSUsername { get; set; }
        public string UPSPassword { get; set; }
        public string FaxNumber { get; set; }
        public string AlternateContact { get; set; }
        public string AlternateEmail { get; set; }
    
        public virtual ICollection<AddressBookInfo> AddressBookInfoes { get; set; }
        public virtual ICollection<CustomerAccount> CustomerAccounts { get; set; }
        public virtual ICollection<CustomerMarkup> CustomerMarkups { get; set; }
        public virtual ICollection<CustomerShipment> CustomerShipments { get; set; }
        public virtual ICollection<CustomerSpInstructionAmount> CustomerSpInstructionAmounts { get; set; }
        public virtual ICollection<ShipmentRequest> ShipmentRequests { get; set; }
        public virtual ICollection<Consignee> Consignees { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
