//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerShipment
    {
        public System.Guid Id { get; set; }
        public System.Guid customerId { get; set; }
        public string trackingNumber { get; set; }
        public System.DateTime createdDate { get; set; }
        public string status { get; set; }
        public string pickupNumber { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public byte[] shipmentLabel { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
