//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount
    {
        public CustomerAccount()
        {
            this.AccessorialChargeAmounts = new HashSet<AccessorialChargeAmount>();
            this.ZoneDiscountPercentages = new HashSet<ZoneDiscountPercentage>();
        }
    
        public string Id { get; set; }
        public int RateYear { get; set; }
        public bool UPSEnabled { get; set; }
        public System.Guid TermId { get; set; }
        public System.Guid CustomerId { get; set; }
    
        public virtual ICollection<AccessorialChargeAmount> AccessorialChargeAmounts { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Term Term { get; set; }
        public virtual ICollection<ZoneDiscountPercentage> ZoneDiscountPercentages { get; set; }
    }
}
