//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int invoiceId { get; set; }
        public string invoiceSubject { get; set; }
        public string invoiceDetails { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public byte[] invoiceFileName { get; set; }
        public System.DateTime dateUpload { get; set; }
        public string username { get; set; }
        public string accountnumber { get; set; }
    }
}
