//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public string NewsTitle { get; set; }
        public System.DateTime NewsDate { get; set; }
        public string NewsCaption { get; set; }
        public string NewsContent { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
