//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostalCode
    {
        public PostalCode()
        {
            this.PostalCodeZones = new HashSet<PostalCodeZone>();
        }
    
        public System.Guid Id { get; set; }
        public string OriginCountry { get; set; }
        public string OriginPostalCodeMin { get; set; }
        public string OriginPostalCodeMax { get; set; }
        public string DestinationCountry { get; set; }
        public string DestinationPostalCodeMin { get; set; }
        public string DestinationPostalCodeMax { get; set; }
    
        public virtual ICollection<PostalCodeZone> PostalCodeZones { get; set; }
    }
}
