//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostalCodeZone
    {
        public System.Guid Id { get; set; }
        public System.Guid PostalCodeId { get; set; }
        public System.Guid ShippingTypeId { get; set; }
        public int ZoneId { get; set; }
    
        public virtual PostalCode PostalCode { get; set; }
        public virtual ShippingType ShippingType { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
