//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class QVShipmentDetail
    {
        public int QVShipmentDetailId { get; set; }
        public Nullable<int> SubscriptionFileId { get; set; }
        public string TrackingNumber { get; set; }
        public string ShipperNumber { get; set; }
        public string ShipmentEvent { get; set; }
        public string ReferenceNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ManifestDate { get; set; }
        public string ShipTo { get; set; }
        public string Service { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Images { get; set; }
        public string SignedBy { get; set; }
        public string ShipToName { get; set; }
        public string ShipToAttention { get; set; }
        public string ShipToAddressLine1 { get; set; }
        public string ShipToAddressLine2 { get; set; }
        public string ShipToTelephoneNumber { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToStateProvince { get; set; }
        public string ShipToPostalCode { get; set; }
        public string ShipToCountry { get; set; }
        public string ExceptionDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
