//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class QVSubscriptionFile
    {
        public int SubscriptionFileId { get; set; }
        public Nullable<int> SyncId { get; set; }
        public string SubscriptionFileName { get; set; }
        public string SubscriptionNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
    }
}
