//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class schema_info_dss
    {
        public int schema_major_version { get; set; }
        public int schema_minor_version { get; set; }
        public string schema_extended_info { get; set; }
    }
}
