//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingType
    {
        public ShippingType()
        {
            this.PostalCodeZones = new HashSet<PostalCodeZone>();
        }
    
        public System.Guid Id { get; set; }
        public string Content { get; set; }
        public string Service { get; set; }
    
        public virtual ICollection<PostalCodeZone> PostalCodeZones { get; set; }
    }
}
