//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skid
    {
        public int Id { get; set; }
        public string SkidDescription { get; set; }
        public double ItemLength { get; set; }
        public double ItemWidth { get; set; }
        public double ItemHeight { get; set; }
        public double SkidVolume { get; set; }
        public double SkidWeight { get; set; }
        public string UnitOfMeasurement { get; set; }
        public string QuotationId { get; set; }
    }
}
