//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkidWeight
    {
        public SkidWeight()
        {
            this.SkidRates = new HashSet<SkidRate>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public decimal Low { get; set; }
        public decimal High { get; set; }
    
        public virtual ICollection<SkidRate> SkidRates { get; set; }
    }
}
