//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialInstruction
    {
        public SpecialInstruction()
        {
            this.CustomerSpInstructionAmounts = new HashSet<CustomerSpInstructionAmount>();
            this.SpecialInstructionAmounts = new HashSet<SpecialInstructionAmount>();
        }
    
        public System.Guid Id { get; set; }
        public string SpecialInstructionName { get; set; }
    
        public virtual ICollection<CustomerSpInstructionAmount> CustomerSpInstructionAmounts { get; set; }
        public virtual ICollection<SpecialInstructionAmount> SpecialInstructionAmounts { get; set; }
    }
}
