//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int LookupId { get; set; }
        public string LookupCode { get; set; }
        public string LookupValue { get; set; }
        public string LookupText { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
