//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public System.Guid Id { get; set; }
        public string TaxName { get; set; }
        public string TaxStateAbbreviation { get; set; }
        public string TaxState { get; set; }
        public decimal TaxPercent { get; set; }
    }
}
