//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.CustomerAccounts = new HashSet<CustomerAccount>();
        }
    
        public System.Guid Id { get; set; }
        public string TermName { get; set; }
    
        public virtual ICollection<CustomerAccount> CustomerAccounts { get; set; }
    }
}
