//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weight
    {
        public Weight()
        {
            this.ZoneRates = new HashSet<ZoneRate>();
        }
    
        public int Id { get; set; }
        public int Low { get; set; }
        public int High { get; set; }
    
        public virtual ICollection<ZoneRate> ZoneRates { get; set; }
    }
}
