//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPS.Sync
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneDiscountPercentage
    {
        public System.Guid Id { get; set; }
        public double Content { get; set; }
        public double PAKDiscountPercentage { get; set; }
        public double LTRDiscountPercentage { get; set; }
        public string CustomerAccountId { get; set; }
        public int ZoneId { get; set; }
    
        public virtual CustomerAccount CustomerAccount { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
